/**
 * lottery_picks.txt - the ML layer's output, and the one file the site reads that is not an
 * artifact.
 *
 * It is generated by quickpick.py on the owner's PC and is NOT on the VPS, which never
 * trains a model. So everything here is optional by design: the public half of Review must
 * not depend on it, and the admin half says plainly when it is absent.
 */
import fs from 'node:fs';
import path from 'node:path';

export interface Pick {
  line: number;
  model: string;
  main: number[];
  bonus: number | null;
}

export interface Picks {
  generated: string | null;
  picks: Pick[];
  wheelLines: number[][];
}

function picksPath(): string {
  return process.env.PICKS_FILE ?? path.join(process.cwd(), '..', 'lottery_picks.txt');
}

export function picksAvailable(): boolean {
  return fs.existsSync(picksPath());
}

const LINE = /^Line (\d+): (.+?) \[/;
const MAIN = /^Main Numbers \(6\): \[([\d, ]+)\]/;
const BONUS = /^Bonus Ball: (\d+)/;
const WHEEL = /^Wheel Line \d+: \[([\d, ]+)\]/;
const GENERATED = /^LOTTERY PICKS - GENERATED (.+)$/;

function numbers(text: string): number[] {
  return text
    .split(',')
    .map((n) => Number(n.trim()))
    .filter((n) => Number.isInteger(n));
}

/** Parses the picks file. Returns null when it is not there. */
export function readPicks(): Picks | null {
  const file = picksPath();
  if (!fs.existsSync(file)) return null;

  const lines = fs.readFileSync(file, 'utf8').split(/\r?\n/);
  const picks: Pick[] = [];
  const wheelLines: number[][] = [];
  let generated: string | null = null;
  let current: Pick | null = null;

  for (const raw of lines) {
    const line = raw.trim();

    const gen = line.match(GENERATED);
    if (gen) generated = gen[1];

    const wheel = line.match(WHEEL);
    if (wheel) {
      wheelLines.push(numbers(wheel[1]));
      continue;
    }

    const header = line.match(LINE);
    if (header) {
      current = { line: Number(header[1]), model: header[2], main: [], bonus: null };
      picks.push(current);
      continue;
    }

    if (!current) continue;

    const main = line.match(MAIN);
    if (main) current.main = numbers(main[1]);

    const bonus = line.match(BONUS);
    if (bonus) current.bonus = Number(bonus[1]);
  }

  return { generated, picks: picks.filter((p) => p.main.length === 6), wheelLines };
}
