# ml_lotto/features/extractor.py
"""
extractor.py
============
Main orchestrator for feature extraction from HMC JSON data.

VERSION: 3.16 (Pairwise & Triple Interaction Features - Dynamic JSON Loading)
- NEW: Pairwise interaction features from feature_interaction_explorer.py analysis
  * Up to 10 binary interaction features (synergistic, strength ≥ 3.0)
  * Win rate of 0.857 when both features are high
  * Dynamically loaded from data/analysis/lotto_feature_interactions.json
- NEW: Optional triple interaction features (category × freshness × recency)
  * Up to 3 triple combinations with highest lift
  * Dynamically loaded from analysis data (no hard-coded values)
- NEW KEYWORDS: 'PAIRWISE_INTERACTIONS', 'TRIPLE_INTERACTIONS', 'ALL_INTERACTIONS'
- NO HARD-CODED DATA: All medians and thresholds loaded from JSON files generated by drawpick.py
- PREVIOUS (v3.12-3.15): Freshness interaction features, long-term patterns, advanced features
"""

import pandas as pd
from typing import Dict, Any, List, Tuple
from ml_lotto.config import MAX_NUMBER, FRESHNESS_PATTERN_WEIGHTS, LONG_TERM_PATTERN_WEIGHTS

from ml_lotto.features.timing import calculate_recency_zone_score, load_recency_zones
from ml_lotto.features.patterns import (
    calculate_has_consecutive_partner,
    calculate_consecutive_pair_affinity
)
from ml_lotto.features.window_saturation import calculate_window_saturation_score
from ml_lotto.features.interactions import calculate_all_interaction_features, get_interaction_feature_names
# NOTE: Removed duplicate calculated features - using JSON versions instead:
# - calculate_bonus_hit_target_alignment → bonus_hit_contribution
# - calculate_odd_even_affinity → odd_even_json
# - calculate_sum_contribution_score → sum_contribution_json
# - calculate_range_spread_affinity → range_spread_json


def extract_features_from_hmc_json(
    hmc_data: Dict[str, Any],
    dynamic_recent_keys: List[Tuple[str, str]],
    days_since_bonus_data: Dict[int, int],
    pattern_score_data: Dict[int, float],
    freshness_features: Dict[int, Dict[str, float]] = None,
    win_bias_ratio_data: Dict[int, float] = None,
    was_recent_bonus_data: Dict[int, int] = None,
    consecutive_patterns: Dict[str, Any] = None,
    distribution_stats: Dict[str, Any] = None,
    odds_data: Dict[str, Any] = None,
    training_start_draw: int = 100,
    bonus_hit_contribution_data: Dict[int, float] = None,
    freshness_weight_data: Dict[int, float] = None,
    pair_frequency_data: Dict[int, float] = None,
    range_spread_json_data: Dict[int, float] = None,
    odd_even_json_data: Dict[int, float] = None,
    sum_contribution_json_data: Dict[int, float] = None,
    long_term_features: Dict[int, Dict[str, float]] = None,
    advanced_pattern_features: Dict[int, Dict[str, float]] = None,
    consecutive_pairs_validated: Dict[str, Any] = None,
    rolling_stats_features: Dict[int, Dict[str, float]] = None
) -> Dict[int, Dict[str, Any]]:
    """
    Extract ML features for each number, incorporating ALL custom features including new JSON features.

    Args:
        hmc_data: HMC statistics from lotto_trigger_periods.json
        dynamic_recent_keys: List of (data_key, ml_key) tuples for recent counts
        days_since_bonus_data: Days since each number was a bonus
        pattern_score_data: Pattern scoring data (deprecated, pass empty dict)
        freshness_features: Pre-calculated freshness category features
        win_bias_ratio_data: Category performance ratios
        was_recent_bonus_data: Recent bonus indicators
        consecutive_patterns: Consecutive pair data from odds JSON
        distribution_stats: Distribution statistics from distribution_stats.json
        odds_data: Odds and pattern data from odds_results.json
        training_start_draw: Starting draw index for training
        bonus_hit_contribution_data: NEW - Bonus hit contribution scores
        freshness_weight_data: NEW - Freshness weight scores
        pair_frequency_data: NEW - Pair frequency scores
        range_spread_json_data: NEW - Range spread from JSON
        odd_even_json_data: NEW - Odd/even affinity from JSON
        sum_contribution_json_data: NEW - Sum contribution from JSON
        long_term_features: NEW - Long-term pattern analysis features
        advanced_pattern_features: NEW - Volatility and trend features (v3.13)
        rolling_stats_features: NEW - Rolling statistics features (v3.14)

    Returns:
        Dictionary mapping number (1-47) -> feature dictionary
    """
    features = {}
    # Determine reference timestamp from latest draw date in hmc_data (reproducible & wall-clock independent)
    ref_dates = []
    for k, v in hmc_data.items():
        if isinstance(v, dict) and 'last_seen' in v:
            try:
                ref_dates.append(pd.to_datetime(v['last_seen'].replace('/', '-')))
            except Exception:
                pass
    current_timestamp = max(ref_dates) if ref_dates else pd.Timestamp.now()
    ml_feature_names = [ml_key for data_key, ml_key in dynamic_recent_keys]

    if freshness_features is None:
        freshness_features = {}

    # Load recency zones for data-driven recency scoring
    recency_zones_json = load_recency_zones()
    if recency_zones_json:
        print("  ✓ Loaded recency zones (data-driven)")
    else:
        print("  ⚠️  Using fallback recency zones (hard-coded)")

    print("  Calculating Priority 2 features...")
    has_consecutive_partner_data = calculate_has_consecutive_partner(
        hmc_data,
        dynamic_recent_keys
    )
    
    consecutive_pair_affinity_data = {}
    if consecutive_patterns:
        try:
            consecutive_pair_affinity_data = calculate_consecutive_pair_affinity(
                consecutive_patterns,
                validated_scores=consecutive_pairs_validated
            )
        except ValueError as e:
            print(f"\n⚠️  Feature extraction stopped due to missing data.")
            raise
    else:
        print(f"\n❌ CRITICAL ERROR: Consecutive patterns data not provided.")
        raise ValueError("Missing consecutive_patterns data - cannot extract features")

    # NOTE: Removed duplicate calculated features - using JSON versions instead
    print("  ✓ Skipped duplicate calculations (using JSON-loaded versions)")
    
    print("  Loading NEW JSON features...")
    
    if bonus_hit_contribution_data is None:
        bonus_hit_contribution_data = {num: 0.5 for num in range(1, MAX_NUMBER + 1)}
        print(f"  ⚠️  Using default bonus_hit_contribution values")
    else:
        print(f"  ✓ Loaded bonus_hit_contribution data")
    
    if freshness_weight_data is None:
        freshness_weight_data = {0: 0.33, 1: 0.33, 2: 0.34}
        print(f"  ⚠️  Using default freshness_weight values")
    else:
        print(f"  ✓ Loaded freshness_weight data")
    
    if pair_frequency_data is None:
        pair_frequency_data = {num: 0.5 for num in range(1, MAX_NUMBER + 1)}
        print(f"  ⚠️  Using default pair_frequency values")
    else:
        print(f"  ✓ Loaded pair_frequency data")
    
    if range_spread_json_data is None:
        range_spread_json_data = {num: 0.5 for num in range(1, MAX_NUMBER + 1)}
        print(f"  ⚠️  Using default range_spread_json values")
    else:
        print(f"  ✓ Loaded range_spread_json data")
    
    if odd_even_json_data is None:
        odd_even_json_data = {num: 0.5 for num in range(1, MAX_NUMBER + 1)}
        print(f"  ⚠️  Using default odd_even_json values")
    else:
        print(f"  ✓ Loaded odd_even_json data")
    
    if sum_contribution_json_data is None:
        sum_contribution_json_data = {num: 0.5 for num in range(1, MAX_NUMBER + 1)}
        print(f"  ⚠️  Using default sum_contribution_json values")
    else:
        print(f"  ✓ Loaded sum_contribution_json data")

    # Load long-term pattern features
    if long_term_features is None:
        long_term_features = {}
        print(f"  ⚠️  No long-term pattern features provided")
    else:
        print(f"  ✓ Loaded long-term pattern features")

    # Load advanced pattern features (v3.13)
    if advanced_pattern_features is None:
        advanced_pattern_features = {}
        print(f"  ⚠️  No advanced pattern features provided")
    else:
        print(f"  ✓ Loaded advanced pattern features (volatility, trend)")

    # Load rolling statistics features (v3.14)
    if rolling_stats_features is None:
        rolling_stats_features = {}
        print(f"  ⚠️  No rolling statistics features provided")
    else:
        print(f"  ✓ Loaded rolling statistics features ({len(rolling_stats_features)} numbers)")

    # Calculate window saturation scores (NEW v3.10)
    print("  Calculating window_saturation_penalty feature...")
    window_saturation_data = {}
    if odds_data:
        try:
            window_saturation_data = calculate_window_saturation_score(
                hmc_data,
                odds_data,
                MAX_NUMBER
            )
            print(f"  ✓ Window saturation penalties calculated for {len(window_saturation_data)} numbers")
        except Exception as e:
            print(f"  ⚠️  Error calculating window saturation: {e}")
            window_saturation_data = {num: 0.0 for num in range(1, MAX_NUMBER + 1)}
    else:
        print(f"  ⚠️  No odds_data provided - using zero saturation penalties")
        window_saturation_data = {num: 0.0 for num in range(1, MAX_NUMBER + 1)}

    print(f"\n✓ Extracting features from HMC data:")
    base_features = ['total_count', 'days_since_last', 'recency_zone_score',
                     'series_total', 'series_recent', 'days_since_bonus',
                     'win_bias_ratio', 'was_recent_bonus', 'has_consecutive_partner',
                     'consecutive_pair_affinity',
                     'bonus_hit_contribution', 'freshness_weight_score', 'pair_frequency_score',
                     'range_spread_json', 'odd_even_json', 'sum_contribution_json']
    fresh_features_names = sorted([k for k in next(iter(freshness_features.values())).keys()
                                   if k.startswith('freshness_c') and k.endswith('_weight')]) if freshness_features and next(iter(freshness_features.values())) else []

    lt_feature_names = ['lt_hot_weight', 'lt_medium_weight', 'lt_cold_weight',
                        'lt_category_alignment', 'lt_recency_weight'] if long_term_features else []

    print(f"  Static features: {base_features}")
    print(f"  Freshness features: {fresh_features_names + ['current_freshness_bin']}")
    print(f"  Dynamic features: {ml_feature_names}")
    if lt_feature_names:
        print(f"  Long-term pattern features: {lt_feature_names}")
    
    for num_str in range(1, MAX_NUMBER + 1):
        num = num_str
        num_key = str(num)
        recent_fields = {f: 0 for f in ml_feature_names}
        
        fresh_feat = freshness_features.get(num, {})
        
        current_freshness_bin = fresh_feat.get('current_freshness_bin', 0)
        freshness_weight_score = freshness_weight_data.get(current_freshness_bin, 0.33)

        # Get long-term features for this number
        lt_feat = long_term_features.get(num, {}) if long_term_features else {}

        # Get advanced pattern features for this number (v3.13)
        adv_feat = advanced_pattern_features.get(num, {}) if advanced_pattern_features else {}

        # Get rolling statistics features for this number (v3.14)
        roll_feat = rolling_stats_features.get(num, {}) if rolling_stats_features else {}

        # Calculate NEW interaction features for defaults
        recent_4_count = recent_fields.get('recent_4', 0)
        freshness_momentum_default = recent_4_count * freshness_weight_score
        freshness_timing_default = current_freshness_bin * (1.0 / 1000.0)  # days_since = 999
        freshness_category_interaction_default = freshness_weight_score * 0.280  # cold category

        default_features = {
            'total_count': 0,
            'category': 'cold',
            'days_since_last': 999,
            'recency_zone_score': calculate_recency_zone_score(999, category='cold', recency_zones_json=recency_zones_json),
            'series_total': 0,
            'series_recent': 0,
            'days_since_bonus': days_since_bonus_data.get(num, 999),
            'win_bias_ratio': win_bias_ratio_data.get(num, 1.0) if win_bias_ratio_data else 1.0,
            'was_recent_bonus': was_recent_bonus_data.get(num, 0) if was_recent_bonus_data else 0,
            'has_consecutive_partner': has_consecutive_partner_data.get(num, 0),
            'consecutive_pair_affinity': consecutive_pair_affinity_data.get(num, 0.5),
            'bonus_hit_contribution': bonus_hit_contribution_data.get(num, 0.5),
            'freshness_weight_score': freshness_weight_score,
            'pair_frequency_score': pair_frequency_data.get(num, 0.5),
            'range_spread_json': range_spread_json_data.get(num, 0.5),
            'odd_even_json': odd_even_json_data.get(num, 0.5),
            'sum_contribution_json': sum_contribution_json_data.get(num, 0.5),
            # NEW v3.12: Interaction features
            'freshness_momentum': freshness_momentum_default,
            'freshness_timing': freshness_timing_default,
            'freshness_category_interaction': freshness_category_interaction_default,
            **fresh_feat,
            **recent_fields,
            **lt_feat,  # Add long-term pattern features
            **adv_feat,  # NEW v3.13: Add advanced pattern features
            **roll_feat,  # NEW v3.14: Add rolling statistics features
        }
        
        if num_key not in hmc_data:
            features[num] = default_features
            continue
        
        num_data = hmc_data[num_key]
        category = num_data.get('category', 'unknown')
        total_count = num_data.get('total_count', 0)
        days_since = 999
        
        if 'last_seen' in num_data:
            try:
                last_date_str = num_data['last_seen'].replace('/', '-')
                last_date = pd.to_datetime(last_date_str)
                days_since = (current_timestamp - last_date).days
            except Exception:
                pass
        
        recent_data = num_data.get('recent', {})
        for data_key, ml_feature_key in dynamic_recent_keys:
            recent_fields[ml_feature_key] = recent_data.get(data_key, 0)
        
        series_total = 0
        series_recent = 0
        
        if 'series' in num_data and 'series' in num_data['series']:
            series_patterns = num_data['series']['series']
            
            for pattern_name, occurrences in series_patterns.items():
                for occurrence in occurrences:
                    series_total += occurrence.get('count', 0)
                    
                    try:
                        end_date_str = occurrence.get('end_date', '').replace('/', '-')
                        end_date = pd.to_datetime(end_date_str)
                        days_ago = (current_timestamp - end_date).days
                        if days_ago <= 60:
                            series_recent += occurrence.get('count', 0)
                    except:
                        pass
        
        # Get long-term features for this number
        lt_feat = long_term_features.get(num, {}) if long_term_features else {}

        # Get advanced pattern features for this number (v3.13)
        adv_feat = advanced_pattern_features.get(num, {}) if advanced_pattern_features else {}

        # Get rolling statistics features for this number (v3.14)
        roll_feat = rolling_stats_features.get(num, {}) if rolling_stats_features else {}

        # Calculate NEW interaction features for better freshness discrimination
        # These replace redundant one-hot encoded weights with meaningful interactions
        recent_4_count = recent_fields.get('recent_4', 0)

        # Freshness momentum: recent count weighted by validated pattern probability
        freshness_momentum = recent_4_count * freshness_weight_score

        # Freshness timing: combines freshness bin with recency (higher = fresher + more recent)
        # Use max() to prevent division by zero if days_since is negative or -1
        freshness_timing = current_freshness_bin * (1.0 / max(days_since + 1, 1))

        # Category alignment: freshness pattern aligned with HMC category performance
        category_weight_map = {'hot': 0.487, 'medium': 0.234, 'cold': 0.280}  # From lt analysis
        category_weight = category_weight_map.get(category, 0.33)
        freshness_category_interaction = freshness_weight_score * category_weight

        features[num] = {
            'total_count': total_count,
            'category': category,
            'days_since_last': days_since,
            'recency_zone_score': calculate_recency_zone_score(days_since, category=category, recency_zones_json=recency_zones_json),
            'series_total': series_total,
            'series_recent': series_recent,
            'days_since_bonus': days_since_bonus_data.get(num, 999),
            'win_bias_ratio': win_bias_ratio_data.get(num, 1.0) if win_bias_ratio_data else 1.0,
            'was_recent_bonus': was_recent_bonus_data.get(num, 0) if was_recent_bonus_data else 0,
            'has_consecutive_partner': has_consecutive_partner_data.get(num, 0),
            'consecutive_pair_affinity': consecutive_pair_affinity_data.get(num, 0.5),
            'bonus_hit_contribution': bonus_hit_contribution_data.get(num, 0.5),
            'freshness_weight_score': freshness_weight_score,
            'pair_frequency_score': pair_frequency_data.get(num, 0.5),
            'range_spread_json': range_spread_json_data.get(num, 0.5),
            'odd_even_json': odd_even_json_data.get(num, 0.5),
            'sum_contribution_json': sum_contribution_json_data.get(num, 0.5),
            'window_saturation_penalty': window_saturation_data.get(num, 0.0),  # NEW v3.10
            # NEW v3.12: Interaction features for better freshness discrimination
            'freshness_momentum': freshness_momentum,
            'freshness_timing': freshness_timing,
            'freshness_category_interaction': freshness_category_interaction,
            **fresh_feat,
            **recent_fields,
            **lt_feat,  # Add long-term pattern features
            **adv_feat,  # NEW v3.13: Add advanced pattern features
            **roll_feat,  # NEW v3.14: Add rolling statistics features
        }

        # NEW v3.16: Add pairwise and triple interaction features (dynamic from JSON)
        # These capture synergistic relationships between features
        # Data loaded from data/analysis/lotto_feature_interactions.json
        try:
            interaction_features = calculate_all_interaction_features(
                features[num],
                include_triples=True  # Include both pairwise and triple interactions
            )
            features[num].update(interaction_features)
        except Exception as e:
            # Silently continue if interaction features fail - they're optional enhancements
            pass

    return features


def get_all_feature_names(features_dict: Dict[int, Dict[str, Any]]) -> List[str]:
    """Get list of all available feature names (excluding 'category')."""
    if not features_dict:
        return []
    
    sample_features = next(iter(features_dict.values()))
    return [key for key in sample_features.keys() if key != 'category']


def expand_feature_selection(feature_spec: Any, all_features: List[str]) -> List[str]:
    """Expand feature specification into actual feature list."""

    # Filter to only include recent_<number> features, exclude others like recent_vs_baseline
    recent_features = sorted([f for f in all_features if f.startswith('recent_') and f.split('_')[1].isdigit()],
                             key=lambda x: int(x.split('_')[1]))

    # DEPRECATED: One-hot encoded freshness weights (kept for backwards compatibility)
    freshness_weights_features_old = sorted([f for f in all_features if f.startswith('freshness_c') and f.endswith('_weight')])

    # NEW v3.12: Interaction features that provide better discrimination
    freshness_interaction_features = [
        'current_freshness_bin',        # Raw bin indicator (0/1/2)
        'freshness_momentum',           # recent_4 * validated_weight
        'freshness_timing',             # bin * (1 / days_since)
        'freshness_category_interaction'  # weight * category_performance
    ]

    # REMOVED v3.13: lt_hot/medium/cold_weight (redundant with days_since_last + category)
    # Category IS defined by recency in HMC system (perfect multicollinearity)
    long_term_pattern_features = ['lt_category_alignment', 'lt_recency_weight']

    # NEW v3.13: Advanced pattern features (volatility and trend)
    advanced_pattern_features_list = [
        'appearance_volatility',     # Coefficient of variation of gaps
        'gap_consistency_score',     # 1/(1+volatility), how consistent
        'max_gap_ratio',             # Max gap / avg gap
        'appearance_trend',          # Recent vs older frequency change
        'appearance_acceleration',   # Very recent vs recent change
        'recent_vs_baseline'         # Recent frequency vs historical baseline
    ]

    new_json_features = ['bonus_hit_contribution', 'freshness_weight_score',
                         'pair_frequency_score', 'range_spread_json',
                         'odd_even_json', 'sum_contribution_json']

    # NEW v3.16: Interaction features (dynamically loaded from JSON)
    # Get interaction feature names from the loaded data
    try:
        pairwise_interaction_features = [f for f in all_features if '_x_' in f and f.endswith('_interaction')]
        triple_interaction_features = [f for f in all_features if f.startswith('triple_')]
        all_interaction_features = pairwise_interaction_features + triple_interaction_features
    except:
        pairwise_interaction_features = []
        triple_interaction_features = []
        all_interaction_features = []

    custom_keywords = {
        'ALL': all_features,
        'RECENT_ALL': recent_features,
        'RECENT_SHORT': recent_features[:1] if recent_features else [],
        'RECENT_LONG': recent_features[-1:] if recent_features else [],
        'BONUS_AWARE': ['days_since_bonus'],
        'FRESHNESS_PATTERN': freshness_weights_features_old,  # Old, kept for compatibility
        FRESHNESS_PATTERN_WEIGHTS: freshness_interaction_features,  # NEW v3.12: Use interaction features
        LONG_TERM_PATTERN_WEIGHTS: long_term_pattern_features,  # UPDATED v3.13: Removed redundant features
        'ADVANCED_PATTERN_FEATURES': advanced_pattern_features_list,  # NEW v3.13: Volatility and trend
        'NEW_JSON_FEATURES': new_json_features,
        # NEW v3.16: Interaction feature keywords
        'PAIRWISE_INTERACTIONS': pairwise_interaction_features,  # Top 10 pairwise interactions
        'TRIPLE_INTERACTIONS': triple_interaction_features,      # Top 3 triple interactions
        'ALL_INTERACTIONS': all_interaction_features             # All interaction features
    }

    if isinstance(feature_spec, str):
        return custom_keywords.get(feature_spec, [])

    if isinstance(feature_spec, list):
        expanded = []
        for item in feature_spec:
            if item in custom_keywords:
                expanded.extend(custom_keywords[item])
            else:
                if item in all_features:
                    expanded.append(item)
        return sorted(set(expanded))

    return []