"""
interactions.py
===============
Composite interaction features discovered by feature_interaction_explorer.py

These binary features capture synergistic relationships between features that
improve prediction accuracy, especially for linear models.

VERSION: 1.0 (Dynamic Data Loading - No Hard-Coded Values)
- All interaction data loaded from JSON files generated by drawpick.py
- No hard-coded medians or thresholds
- Interaction features are recalculated every time drawpick.py runs
- Gracefully handles missing files with fallback defaults
"""

import json
from pathlib import Path
from typing import Dict, Any, List, Tuple


class InteractionFeatureCalculator:
    """
    Calculates interaction features dynamically from JSON data files.

    This class loads interaction analysis data generated by feature_interaction_explorer.py
    and calculates binary interaction features for individual numbers.
    """

    def __init__(self, interaction_json_path: str = None):
        """
        Initialize the calculator with data from JSON files.

        Args:
            interaction_json_path: Path to lotto_feature_interactions.json
                                  If None, uses default path
        """
        if interaction_json_path is None:
            interaction_json_path = "data/analysis/lotto_feature_interactions.json"

        self.interaction_data = self._load_interaction_data(interaction_json_path)
        self.pairwise_interactions = self._extract_pairwise_interactions()
        self.triple_interactions = self._extract_triple_interactions()
        self.feature_medians = self._extract_feature_medians()

    def _load_interaction_data(self, json_path: str) -> Dict[str, Any]:
        """Load interaction analysis data from JSON file."""
        try:
            with open(json_path, 'r') as f:
                data = json.load(f)
            return data
        except (FileNotFoundError, json.JSONDecodeError) as e:
            print(f"⚠️  Warning: Could not load {json_path}: {e}")
            print("   Interaction features will use safe defaults")
            return {
                'pairwise_interactions': [],
                'triple_interactions': [],
                'recommended_composite_features': []
            }

    def _extract_pairwise_interactions(self) -> List[Dict[str, Any]]:
        """Extract top pairwise interactions from loaded data."""
        pairwise = self.interaction_data.get('pairwise_interactions', [])
        # Get top 10 strongest interactions
        return sorted(pairwise, key=lambda x: x.get('interaction_strength', 0), reverse=True)[:10]

    def _extract_triple_interactions(self) -> List[Dict[str, Any]]:
        """Extract top triple interactions from loaded data."""
        triples = self.interaction_data.get('triple_interactions', [])
        # Get top 3 highest lift combinations
        return sorted(triples, key=lambda x: x.get('lift_over_baseline', 0), reverse=True)[:3]

    def _extract_feature_medians(self) -> Dict[str, float]:
        """
        Extract median values from pairwise interactions.

        These medians define the "high/low" split for each feature.
        """
        medians = {}

        for interaction in self.pairwise_interactions:
            feat1 = interaction.get('feature_1')
            feat2 = interaction.get('feature_2')

            if feat1 and feat1 not in medians:
                medians[feat1] = interaction.get('median_1', 0)

            if feat2 and feat2 not in medians:
                medians[feat2] = interaction.get('median_2', 0)

        return medians

    def calculate_pairwise_interactions(self, features: Dict[str, Any]) -> Dict[str, int]:
        """
        Calculate binary pairwise interaction features.

        Returns 1 if both features are >= their median, 0 otherwise.
        All interactions are synergistic (win rate = 0.857 when both high).

        Args:
            features: Dictionary of feature values for a single number

        Returns:
            Dictionary of interaction features (0 or 1)
        """
        interactions = {}

        for interaction in self.pairwise_interactions:
            feat1 = interaction.get('feature_1')
            feat2 = interaction.get('feature_2')

            if not feat1 or not feat2:
                continue

            # Get feature values with defaults
            val1 = features.get(feat1, 0)
            val2 = features.get(feat2, 0)

            # Get medians from the loaded data
            median1 = interaction.get('median_1', 0)
            median2 = interaction.get('median_2', 0)

            # Binary interaction: 1 if both >= median, 0 otherwise
            both_high = 1 if (val1 >= median1 and val2 >= median2) else 0

            # Feature name
            interaction_name = f"{feat1}_x_{feat2}_interaction"
            interactions[interaction_name] = both_high

        return interactions

    def calculate_triple_interactions(self, features: Dict[str, Any]) -> Dict[str, int]:
        """
        Calculate triple interaction features (category × freshness × recency).

        Returns 1 if the combination matches a high-performing triple, 0 otherwise.

        Args:
            features: Dictionary of feature values for a single number

        Returns:
            Dictionary of triple interaction features (0 or 1)
        """
        interactions = {}

        category = features.get('category', 'cold')
        freshness_bin = features.get('freshness_bin', 0)
        days_since = features.get('days_since_last', 999)

        # Define recency zones (same as in feature_interaction_explorer.py)
        if days_since <= 7:
            recency = 'very_recent'
        elif days_since <= 21:
            recency = 'recent'
        elif days_since <= 60:
            recency = 'moderate'
        else:
            recency = 'old'

        # Check each triple combination from loaded data
        for triple in self.triple_interactions:
            cat = triple.get('category')
            fresh = triple.get('freshness_bin')
            rec = triple.get('recency')

            if cat and fresh is not None and rec:
                match = 1 if (category == cat and freshness_bin == fresh and recency == rec) else 0
                interaction_name = f'triple_{cat}_{fresh}_{rec}'
                interactions[interaction_name] = match

        return interactions

    def calculate_all_interaction_features(self,
                                         features: Dict[str, Any],
                                         include_triples: bool = False) -> Dict[str, Any]:
        """
        Calculate all interaction features for a number.

        Args:
            features: Dictionary of feature values for a single number
            include_triples: Whether to include triple interactions (default: False)

        Returns:
            Dictionary containing all interaction features
        """
        all_interactions = {}

        # Add pairwise interactions
        all_interactions.update(self.calculate_pairwise_interactions(features))

        # Optionally add triple interactions
        if include_triples:
            all_interactions.update(self.calculate_triple_interactions(features))

        return all_interactions

    def get_interaction_feature_names(self, include_triples: bool = False) -> List[str]:
        """
        Get list of all interaction feature names.

        Args:
            include_triples: Whether to include triple interactions

        Returns:
            List of feature names
        """
        feature_names = []

        # Pairwise interaction names
        for interaction in self.pairwise_interactions:
            feat1 = interaction.get('feature_1')
            feat2 = interaction.get('feature_2')
            if feat1 and feat2:
                feature_names.append(f"{feat1}_x_{feat2}_interaction")

        # Triple interaction names (if requested)
        if include_triples:
            for triple in self.triple_interactions:
                cat = triple.get('category')
                fresh = triple.get('freshness_bin')
                rec = triple.get('recency')
                if cat and fresh is not None and rec:
                    feature_names.append(f'triple_{cat}_{fresh}_{rec}')

        return feature_names


# Global singleton instance (lazy-loaded)
_global_calculator = None


def get_interaction_calculator(interaction_json_path: str = None) -> InteractionFeatureCalculator:
    """
    Get or create the global interaction calculator instance.

    Args:
        interaction_json_path: Path to interaction data JSON (optional)

    Returns:
        InteractionFeatureCalculator instance
    """
    global _global_calculator

    if _global_calculator is None:
        _global_calculator = InteractionFeatureCalculator(interaction_json_path)

    return _global_calculator


def calculate_all_interaction_features(features: Dict[str, Any],
                                       include_triples: bool = False,
                                       interaction_json_path: str = None) -> Dict[str, Any]:
    """
    Calculate all interaction features for a number (convenience function).

    Args:
        features: Dictionary of feature values for a single number
        include_triples: Whether to include triple interactions (default: False)
        interaction_json_path: Path to interaction data JSON (optional)

    Returns:
        Dictionary containing all interaction features
    """
    calculator = get_interaction_calculator(interaction_json_path)
    return calculator.calculate_all_interaction_features(features, include_triples)


def get_interaction_feature_names(include_triples: bool = False,
                                  interaction_json_path: str = None) -> List[str]:
    """
    Get list of all interaction feature names (convenience function).

    Args:
        include_triples: Whether to include triple interactions
        interaction_json_path: Path to interaction data JSON (optional)

    Returns:
        List of feature names
    """
    calculator = get_interaction_calculator(interaction_json_path)
    return calculator.get_interaction_feature_names(include_triples)
