"""
long_term_patterns.py
====================
Long-term pattern analysis features for identifying stable trends.

This module loads statistically validated long-term patterns generated by
lotto_analysis/analyzers/long_term_pattern_analyzer.py (uses scipy stats).

Features in this module:
- HMC pattern alignment weights (chi-square validated)
- Category-based long-term recency weights (correlation validated)
- Historical performance weights (statistically significant)

All features use data from lotto_long_term_patterns.json (generated by analyzer).
"""

from typing import Dict, Any, List
from collections import Counter
from ml_lotto.config import MAX_NUMBER


def calculate_long_term_hmc_pattern_weights(
    hmc_data: Dict[str, Any],
    long_term_analysis: Dict[str, Any]
) -> Dict[int, Dict[str, float]]:
    """
    Calculate long-term HMC pattern alignment weights using statistically validated data.

    Uses weights derived from chi-square analysis of historical HMC patterns
    performed by long_term_pattern_analyzer.py.

    Args:
        hmc_data: HMC statistics from lotto_trigger_periods.json
        long_term_analysis: Statistical analysis from lotto_long_term_patterns.json

    Returns:
        Dictionary mapping number -> long-term pattern feature dictionary
        Each feature dict contains:
        - lt_hot_weight: Weight for hot numbers (statistically derived)
        - lt_medium_weight: Weight for medium numbers (statistically derived)
        - lt_cold_weight: Weight for cold numbers (statistically derived)
        - lt_category_alignment: Overall alignment score for number's category
        - lt_statistical_confidence: P-value from chi-square test
    """
    # Extract statistically validated category weights
    hmc_analysis = long_term_analysis.get('hmc_pattern_analysis', {})
    category_weights = hmc_analysis.get('category_weights', {
        'hot': 0.33,
        'medium': 0.34,
        'cold': 0.33
    })

    hot_weight = category_weights.get('hot', 0.33)
    medium_weight = category_weights.get('medium', 0.34)
    cold_weight = category_weights.get('cold', 0.33)

    # Get statistical confidence metrics
    chi2_pvalue = hmc_analysis.get('p_value', 1.0)
    is_significant = hmc_analysis.get('significant', False)

    print(f"\n✓ Long-Term HMC Pattern Analysis (Statistical):")
    print(f"  Total patterns analyzed: {hmc_analysis.get('num_patterns', 0)}")
    print(f"  Chi-square p-value: {chi2_pvalue:.4f}")
    print(f"  Statistically significant: {is_significant} (p < 0.05)")
    print(f"  Validated category weights:")
    print(f"    Hot weight: {hot_weight*100:.1f}%")
    print(f"    Medium weight: {medium_weight*100:.1f}%")
    print(f"    Cold weight: {cold_weight*100:.1f}%")

    # Assign weights to each number based on their category
    features = {}
    category_counts = Counter()

    for num in range(1, MAX_NUMBER + 1):
        num_key = str(num)
        category = 'cold'  # Default

        if num_key in hmc_data:
            category = hmc_data[num_key].get('category', 'cold')

        category_counts[category] += 1

        # All numbers get all weights, but alignment shows which applies
        category_alignment = {
            'hot': hot_weight,
            'medium': medium_weight,
            'cold': cold_weight
        }.get(category, 0.33)

        features[num] = {
            'lt_hot_weight': hot_weight,
            'lt_medium_weight': medium_weight,
            'lt_cold_weight': cold_weight,
            'lt_category_alignment': category_alignment,
            'lt_statistical_confidence': 1.0 - chi2_pvalue,  # Higher = more confident
            'lt_category': category
        }

    print(f"\n  Current number distribution:")
    print(f"    Hot: {category_counts['hot']} numbers")
    print(f"    Medium: {category_counts['medium']} numbers")
    print(f"    Cold: {category_counts['cold']} numbers")

    return features


def calculate_long_term_recency_weights(
    hmc_data: Dict[str, Any],
    long_term_analysis: Dict[str, Any],
    all_draws: List[Dict[str, Any]]
) -> Dict[int, float]:
    """
    Calculate long-term recency pattern weights using correlation analysis.

    Uses Pearson correlation coefficients from statistical analysis to
    weight numbers based on their days-since-last-hit and category.

    Args:
        hmc_data: HMC statistics from lotto_trigger_periods.json
        long_term_analysis: Statistical analysis from lotto_long_term_patterns.json
        all_draws: Draw history for calculating current days since last

    Returns:
        Dictionary mapping number -> long-term recency weight (0.0 to 1.0)
    """
    recency_analysis = long_term_analysis.get('recency_correlation_analysis', {})
    by_category = recency_analysis.get('by_category', {})

    if not by_category:
        print("\n⚠️  WARNING: No recency correlation data found")
        return {num: 0.5 for num in range(1, MAX_NUMBER + 1)}

    # Get recency bins for lookup
    recency_bins = recency_analysis.get('recency_bins', [
        {'name': '0-7 days', 'min': 0, 'max': 7},
        {'name': '8-14 days', 'min': 8, 'max': 14},
        {'name': '15-21 days', 'min': 15, 'max': 21},
        {'name': '22-30 days', 'min': 22, 'max': 30},
        {'name': '31-45 days', 'min': 31, 'max': 45},
        {'name': '46-60 days', 'min': 46, 'max': 60},
        {'name': '61-90 days', 'min': 61, 'max': 90},
        {'name': '91-120 days', 'min': 91, 'max': 120},
        {'name': '121+ days', 'min': 121, 'max': 999}
    ])

    # Calculate current days_since for each number
    current_days_since = {}
    latest_draw_index = max(draw['draw_index'] for draw in all_draws) if all_draws else 0

    for num in range(1, MAX_NUMBER + 1):
        num_key = str(num)
        days_since = 999  # Default: very old

        if num_key in hmc_data and 'last_seen' in hmc_data[num_key]:
            # Approximate: use draw indices as proxy for days
            for draw in reversed(all_draws):
                if num in draw.get('numbers', []):
                    draws_ago = latest_draw_index - draw['draw_index']
                    days_since = draws_ago * 3  # Approximate: 3 days per draw
                    break

        current_days_since[num] = days_since

    # Calculate weights based on statistically validated recency ranges
    weights = {}

    for num in range(1, MAX_NUMBER + 1):
        num_key = str(num)
        category = 'cold'

        if num_key in hmc_data:
            category = hmc_data[num_key].get('category', 'cold')

        days_since = current_days_since[num]

        # Get category-specific recency data
        category_data = by_category.get(category, {})
        recency_ranges = category_data.get('recency_ranges', {})

        # Find the matching range and get its win rate
        weight = 0.5  # Default

        for bin_info in recency_bins:
            bin_name = bin_info['name']
            min_days = bin_info['min']
            max_days = bin_info['max']

            if min_days <= days_since <= max_days:
                bin_stats = recency_ranges.get(bin_name, {})
                # Use win_rate if available, otherwise default
                weight = bin_stats.get('win_rate', 0.5)
                # Normalize to 0-1 range (win_rate may be higher in some cases)
                weight = min(1.0, weight)
                break

        weights[num] = weight

    # Print correlation statistics
    print(f"\n✓ Long-Term Recency Correlation Analysis:")
    for category in ['hot', 'medium', 'cold']:
        if category in by_category:
            corr = by_category[category].get('correlation', 0.0)
            pval = by_category[category].get('p_value', 1.0)
            sig = by_category[category].get('significant', False)
            print(f"  {category.capitalize()}: correlation={corr:.3f}, p={pval:.4f}, sig={sig}")

    return weights


def expand_long_term_features(
    hmc_data: Dict[str, Any],
    long_term_analysis: Dict[str, Any],
    all_draws: List[Dict[str, Any]]
) -> Dict[int, Dict[str, Any]]:
    """
    Main entry point for calculating all long-term pattern features.

    Uses statistically validated analysis from long_term_pattern_analyzer.py
    instead of performing its own calculations.

    Args:
        hmc_data: HMC statistics from lotto_trigger_periods.json
        long_term_analysis: Statistical analysis from lotto_long_term_patterns.json
        all_draws: Draw history

    Returns:
        Dictionary mapping number -> combined long-term feature dictionary
    """
    print("\n" + "="*60)
    print("LONG-TERM PATTERN ANALYSIS (Statistical Features)")
    print("="*60)

    # Verify we have statistical analysis
    if not long_term_analysis or 'hmc_pattern_analysis' not in long_term_analysis:
        print("\n⚠️  WARNING: No statistical analysis found!")
        print("   Run: python lotto_analysis/analyzers/long_term_pattern_analyzer.py")
        print("   Falling back to default weights...")

        # Return default features
        return {num: {
            'lt_hot_weight': 0.33,
            'lt_medium_weight': 0.34,
            'lt_cold_weight': 0.33,
            'lt_category_alignment': 0.5,
            'lt_recency_weight': 0.5,
            'lt_statistical_confidence': 0.0
        } for num in range(1, MAX_NUMBER + 1)}

    # Calculate HMC pattern weights (statistically validated)
    hmc_features = calculate_long_term_hmc_pattern_weights(hmc_data, long_term_analysis)

    # Calculate recency weights (correlation validated)
    recency_weights = calculate_long_term_recency_weights(hmc_data, long_term_analysis, all_draws)

    # Combine all features
    combined = {}
    for num in range(1, MAX_NUMBER + 1):
        combined[num] = {
            **hmc_features.get(num, {}),
            'lt_recency_weight': recency_weights.get(num, 0.5)
        }

    print("\n✓ Long-term statistical features calculated for all 47 numbers")
    print("="*60 + "\n")

    return combined

