"""
timing.py
=========
Time-based feature calculations.

Features in this module:
- days_since_bonus: Days since number was last drawn as bonus
- recency_zone_score: Score based on optimal recency windows (data-driven)
"""

import json
import os
from datetime import datetime
from typing import Dict, Any, List, Optional
from pathlib import Path
from ml_lotto.config import MAX_NUMBER


def calculate_days_since_bonus(all_draws: List[Dict[str, Any]]) -> Dict[int, int]:
    """
    Calculate the days since each number was last drawn as a bonus ball.
    
    Scans historical draws in reverse order to find the most recent date
    each number appeared as the bonus ball.
    
    Args:
        all_draws: List of draw dictionaries from lotto_draw_history.json
        
    Returns:
        Dictionary mapping number -> days_since_bonus (999 if never)
    """
    now = datetime.now()
    days_since_bonus = {num: 999 for num in range(1, MAX_NUMBER + 1)}
    last_seen_date = {num: None for num in range(1, MAX_NUMBER + 1)}
    
    for draw in reversed(all_draws):
        draw_date = datetime.strptime(draw['date'], "%Y-%m-%d")
        bonus_num = draw.get('bonus_number')
        
        if bonus_num is not None and 1 <= bonus_num <= MAX_NUMBER:
            if last_seen_date[bonus_num] is None:
                last_seen_date[bonus_num] = draw_date

    for num in range(1, MAX_NUMBER + 1):
        if last_seen_date[num] is not None:
            days_since = (now - last_seen_date[num]).days
            days_since_bonus[num] = max(0, days_since)
    
    print(f"✓ Custom feature 'days_since_bonus' calculated.")
    return days_since_bonus


def load_recency_zones(json_path: Optional[str] = None) -> Optional[Dict[str, Any]]:
    """
    Load recency zones from JSON file.

    Args:
        json_path: Optional path to JSON file. If not provided, uses default path.

    Returns:
        Recency zones data or None if file not found
    """
    if json_path is None:
        # Default path: data/lotto_recency_zones_calculated.json
        project_root = Path(__file__).parent.parent.parent
        json_path = project_root / 'data' / 'lotto_recency_zones_calculated.json'

    try:
        if os.path.exists(json_path):
            with open(json_path, 'r') as f:
                return json.load(f)
    except Exception as e:
        print(f"⚠️  Warning: Could not load recency zones from {json_path}: {e}")

    return None


def calculate_recency_zone_score(
    days_since_last: int,
    category: Optional[str] = None,
    recency_zones_json: Optional[Dict[str, Any]] = None
) -> float:
    """
    Score based on data-driven optimal recency windows.

    This function now loads recency zones from JSON data generated by
    recency_zone_analyzer.py, which analyzes historical win rates.

    DATA-DRIVEN ZONES (from lotto_recency_zones_calculated.json):
    - 0-14 days:   47.5% of winners → score 1.0
    - 15-30 days:  24.4% of winners → score 0.51
    - 31-60 days:  21.2% of winners → score 0.45
    - 61-120 days: 6.3% of winners  → score 0.13
    - 121+ days:   0.7% of winners  → score 0.01

    Category-aware scoring reveals:
    - HOT numbers: 99.9% appear in 0-14 days
    - MEDIUM numbers: 100% appear in 15-30 days
    - COLD numbers: 75.4% appear in 31-60 days

    Args:
        days_since_last: Number of days since last appearance
        category: Optional category (hot/medium/cold) for category-aware scoring
        recency_zones_json: Optional pre-loaded JSON data (for performance)

    Returns:
        Score from 0.0 to 1.0 (higher = better timing)
    """
    # Load zones from JSON if available
    if recency_zones_json is None:
        recency_zones_json = load_recency_zones()

    if recency_zones_json:
        # Use category-specific zones if category provided and available
        if category and 'recency_zones_by_category' in recency_zones_json:
            zones = recency_zones_json['recency_zones_by_category'].get(category, {})
            if not zones:
                # Fallback to combined zones if category not found
                zones = recency_zones_json.get('recency_zones_combined', {})
        else:
            # Use combined zones (category-agnostic)
            zones = recency_zones_json.get('recency_zones_combined', {})

        # Find matching zone
        for zone_name, zone_data in zones.items():
            if '-' in zone_name:
                # Parse range like "0-14" or "15-30"
                parts = zone_name.split('-')
                min_days = int(parts[0])
                max_days = int(parts[1])
            elif '+' in zone_name:
                # Parse range like "121+"
                min_days = int(zone_name.replace('+', ''))
                max_days = 999999  # Very large number for "infinity"
            else:
                continue

            if min_days <= days_since_last <= max_days:
                return zone_data['score']

        # If no match found, return minimum score
        return 0.01

    # Fallback to hard-coded values if JSON not available
    return _calculate_recency_zone_score_fallback(days_since_last)


def _calculate_recency_zone_score_fallback(days_since_last: int) -> float:
    """
    Fallback to hard-coded values if JSON not available.

    These are the original hard-coded thresholds that have been replaced
    by data-driven values from recency_zone_analyzer.py.

    Args:
        days_since_last: Number of days since last appearance

    Returns:
        Score from 0.0 to 1.0 (higher = better timing)
    """
    if 0 <= days_since_last <= 14:
        return 1.0
    elif 14 < days_since_last <= 30:
        return 0.78
    elif 30 < days_since_last <= 60:
        return 0.54
    elif 60 < days_since_last <= 120:
        return 0.18
    else:
        return 0.01