# ml_lotto/config.py
"""
Configuration settings for lottery analysis

VERSION: 3.16c (C-5: full-history constant features removed)
- REMOVED from all four model feature lists: odd_even_json, range_spread_json,
  sum_contribution_json, window_saturation_penalty, series_recent and the
  LONG_TERM_PATTERN_WEIGHTS group (lt_category_alignment, lt_recency_weight).
  Each was a per-number statistic estimated over the whole timeline - including the
  validation window - so it leaked outcome information and carried no temporal signal.
  Removing them left validation ranking unchanged (every delta < 2 SE) and cut the
  Jackpot Optimizer's train/val AUC gap from 0.380 to 0.148. The odd/even, sum and
  range constraints they were meant to express are enforced in prediction/filters.py,
  which is where they belong. See issue.md.

VERSION: 3.16b (ML-Optimized Model 1 with Interaction Features)
- UPDATED: Model 1 selects all 6 numbers via ML (no pre-assignment)
  * Pre-assigned bonus and bonus-to-main numbers removed from line selection
  * Configured hot_count: 4, medium_count: 1, cold_count: 1 (total: 6 numbers)
  * Optimized feature set: removed redundant features (total_count, recent_14, lt features)
  * Kept high-importance features: appearance_volatility (0.38), current_freshness_bin (0.32), etc.
- NEW: Triple interactions added to Model 1
  * PAIRWISE_INTERACTIONS: 10 synergistic binary features
  * TRIPLE_INTERACTIONS: 3 category × freshness × recency combinations
  * Total: ~25 features (down from 30, reduced redundancy)
- Models 2 & 3: Unchanged
- Result: Interaction features now have room to show their value
"""

# ============================================================================
# RANDOM SEED CONFIGURATION - ENSEMBLE MODE
# ============================================================================
# ENSEMBLE MODE: Run models multiple times with different random seeds
# to identify numbers that are CONSISTENTLY ranked high across runs.
#
# Benefits of ensemble voting:
#   - See which numbers are "robustly" strong picks
#   - Numbers appearing in 80%+ of runs are very confident picks
#   - Numbers appearing in 50% of runs are uncertain/borderline
#   - More reliable than single random initialization
#
# Configuration:
ENSEMBLE_MODE = False # Set to True to enable ensemble mode in quickpick.py (not used currently)
ENSEMBLE_RUNS = 15    # Number of runs for ensemble.py script (recommend 10-20)
RANDOM_SEED_BASE = 42 # Base seed - fixed for deterministic results

# Dynamic random seed (will be updated for each ensemble run)
# This is what model configs will use
_CURRENT_RANDOM_SEED = RANDOM_SEED_BASE

TOTAL_DRAWS = None         # Total number of draws to analyze (None = all available)
TRAINING_DATA = 100        # Initial training window size for HMC analysis
NUM_DRAWS = None           # Dynamically calculated from available draws
TRAINING_START_DRAW = TRAINING_DATA

# Train/Validation Split Configuration: Hold out latest 15% of historical draws for validation metrics
VALIDATION_SPLIT_RATIO = 0.85

DRAW_HISTORY_JSON = 'data/lotto_draw_history.json'
HMC_JSON_INPUT = 'data/lotto_trigger_periods.json'
ODDS_JSON_INPUT = 'data/lotto_odds_results.json'
FRESHNESS_JSON_INPUT = 'data/lotto_7_number_freshness_results.json'
DISTRIBUTION_STATS_JSON = 'data/lotto_distribution_stats.json'
BONUS_ANALYSIS_JSON = 'data/lotto_bonus_analysis.json'
BONUS_TO_MAIN_JSON = 'data/lotto_bonus_to_main_patterns.json'
LONG_TERM_PATTERNS_JSON = 'data/lotto_long_term_patterns.json'  # Generated by long_term_pattern_analyzer.py
ADVANCED_PATTERNS_JSON = 'data/lotto_advanced_patterns.json'  # NEW v3.13: Volatility and trend features
STATISTICS_ANALYSIS_JSON = 'data/lotto_statistics_analysis.json'  # Legacy compatibility
WINDOW_SATURATION_CALCULATED_JSON = 'data/lotto_window_saturation_calculated.json'  # Generated by window_saturation_analyzer.py - DATA-DRIVEN penalties from real saturation rates

# Scipy-validated analysis files
FRESHNESS_PATTERNS_VALIDATED_JSON = 'data/lotto_freshness_patterns_validated.json'  # Scipy chi-square validation
HMC_CATEGORIZATION_VALIDATED_JSON = 'data/lotto_hmc_categorization_validated.json'  # Scipy ANOVA validation
CONSECUTIVE_PAIRS_VALIDATED_JSON = 'data/lotto_consecutive_pairs_validated.json'  # Scipy independence tests
ODD_EVEN_VALIDATED_JSON = 'data/lotto_odd_even_validated.json'  # Scipy chi-square and binomial tests
SUM_CONTRIBUTION_VALIDATED_JSON = 'data/lotto_sum_contribution_validated.json'  # Scipy t-tests and ANOVA
RANGE_SPREAD_VALIDATED_JSON = 'data/lotto_range_spread_validated.json'  # Scipy Levene's test and t-tests

MAX_NUMBER = 47
HOT_COUNT = 15
COLD_COUNT = 15

# CRITICAL FIX: Synchronized with lotto_analysis/config/config.py
# These must match for feature extraction to align with data generation
SCENARIOS = [
    {"window": 5,  "targets": [2]},
    {"window": 6,  "targets": [3]},
    {"window": 10, "targets": [4]},
    {"window": 25, "targets": [8]}
]

ACTUAL_HISTORY_WINDOWS = [s["window"] for s in SCENARIOS]

RANGE_BINS = {
    "20-25": (20, 25),
    "25-30": (25, 30),
    "30-35": (30, 35),
    "35-40": (35, 40),
    "40-45": (40, 45)
}

FRESHNESS_PATTERN_WEIGHTS = 'FRESHNESS_PATTERN_WEIGHTS'
LONG_TERM_PATTERN_WEIGHTS = 'LONG_TERM_PATTERN_WEIGHTS'
ADVANCED_PATTERN_FEATURES = 'ADVANCED_PATTERN_FEATURES'  # NEW v3.13: Volatility and trend

BONUS_MODEL_CONFIG = {
    'name': 'Bonus Ball Predictor',
    'algorithm': 'logistic_regression',
    'features': [
        # === BONUS-SPECIFIC FEATURES (8) ===
        'category_weight',              # HMC category preference for bonus
        'was_bonus_last_10',           # Recent exclusion pattern
        'freshness_weight',            # Freshness preference for bonus
        'timing_zone_weight',          # Optimal timing zones
        'days_since_last_bonus',       # Recency of last bonus appearance
        'bonus_frequency_ratio',       # Historical bonus rate
        'total_bonus_count',           # Total bonus appearances
        'avg_days_between_bonus',      # Pattern regularity

        # === MAIN FEATURES - TEMPORAL PATTERNS (3) ===
        'rolling_rate_10',              # Recent bonus momentum (10 draws)
        'rolling_rate_20',              # Medium-term bonus trend (20 draws)
        'rolling_trend_10',             # Bonus acceleration (heating up?)

        # === MAIN FEATURES - GAP PATTERNS (3) ===
        'gap_consistency_score',        # Predictable bonus appearance cycles
        'gap_variance',                 # Bonus pattern stability
        'max_gap_ratio',                # Current gap vs historical max

        # === MAIN FEATURES - RECENT ACTIVITY (2) ===
        'recent_4',                     # Recent main appearances (saturation)
        'recent_14',                    # Medium-term main appearances

        # === MAIN FEATURES - BASELINE (3) ===
        'total_count',                  # Overall popularity as main ball
        'appearance_volatility',        # Frequency consistency
        'category',                     # HMC category (for interactions)
        'freshness_bin',                # Freshness bin (for interactions)

        # === INTERACTION FEATURES (~13) ===
        'PAIRWISE_INTERACTIONS',        # Critical for logistic regression!
        'TRIPLE_INTERACTIONS',          # Category × freshness × recency patterns
    ],
    # Total: 8 bonus + 12 main + ~13 interactions = ~33 features

    # L1, not L2. With 32 features against 337 positive training rows the L2 model
    # carried a 0.135 train/val AUC gap, and shrinking C did not move it: L2 scales
    # coefficients but preserves their ranking, and AUC only sees the ranking. L1
    # zeroes features outright - 5 survive at C=0.05, and the gap closes to 0.005
    # (C-15b, extended to the remaining models).
    'algorithm_params': {
        'penalty': 'l1',
        'C': 0.05,
        'solver': 'liblinear',
        'max_iter': 1000,
        'random_state': 42  # Fixed for reproducibility - predictions change only when data changes
    },
    'calibration': None
}

BONUS_TO_MAIN_MODEL_CONFIG = {
    'name': 'Bonus-to-Main Transition Predictor',
    'description': '74% of bonus numbers appear as main within 10 draws (3.48x boost over random)',
    'algorithm': 'logistic_regression',
    'features': [
        # === BONUS-TO-MAIN SPECIFIC FEATURES (12) ===
        'is_in_bonus_window',          # Binary: in recent 10 bonus draws
        'draws_since_bonus',           # Timing: 0-9 draws ago
        'historical_transition_rate',  # Number's historical success rate
        'category_multiplier',         # Hot/medium/cold weight
        'freshness_multiplier',        # Freshness category weight
        'timing_decay_weight',         # Time-based decay (draw_1 strongest)
        'composite_transition_score',  # Combined probability score
        'window_saturation_penalty',   # Window over-saturation penalty
        'avg_draws_to_transition',     # Number's typical transition timing
        'recent_4',                    # Recent main appearances (4 draws)
        'recent_9',                    # Recent main appearances (9 draws)
        'total_count',                 # Overall frequency

        # === MAIN FEATURES - TEMPORAL PATTERNS (4) ===
        'days_since_last',             # CRITICAL: Saturation indicator (was missing!)
        'rolling_rate_10',             # Recent momentum (10 draws)
        'rolling_rate_20',             # Medium-term trend (20 draws)
        'rolling_trend_10',            # Acceleration (heating up?)

        # === MAIN FEATURES - GAP PATTERNS (3) ===
        'gap_consistency_score',       # Predictable appearance cycles
        'gap_variance',                # Pattern stability
        'max_gap_ratio',               # Current gap vs historical max

        # === MAIN FEATURES - BASELINE (3) ===
        'appearance_volatility',       # Frequency consistency
        'category',                    # HMC category (for interactions)
        'freshness_bin',               # Freshness bin (for interactions)

        # === INTERACTION FEATURES (~13) ===
        'PAIRWISE_INTERACTIONS',       # Critical for logistic regression!
        'TRIPLE_INTERACTIONS',         # Category × freshness × timing patterns
    ],
    # Total: 12 bonus-to-main + 10 main + ~13 interactions = ~35 features

    # L1 for the same reason as the bonus model: 35 features against 462 positive
    # training rows gave a 0.150 gap that L2 could not touch. 2 features survive at
    # C=0.005 and the gap falls to 0.033.
    'algorithm_params': {
        'penalty': 'l1',
        'C': 0.005,
        'class_weight': {0: 1.0, 1: 3.5},  # Reflect 3.5x boost over random
        'solver': 'liblinear',
        'max_iter': 1000,
        'random_state': 42  # Fixed for reproducibility - predictions change only when data changes
    },
    'calibration': {
        'method': 'isotonic',  # Better for skewed distributions
        'cv': 5
    }
}

MODEL_1_CONFIG = {
    'name': 'Momentum Specialist',
    'description': 'Focus on recency and momentum - predicts hot/trending numbers across all 7 positions',
    'algorithm': 'logistic_regression',

    # 6 ML-selected numbers (system always selects 6)
    'hot_count': 4,
    'medium_count': 1,
    'cold_count': 1,
    'generic_count': 0,

    'features': [
        # CORE MOMENTUM (MUST HAVE)
        'days_since_last',              # PRIMARY: Recency is key predictor
        'total_count',                  # Frequency matters for momentum

        # ROLLING STATISTICS (MOMENTUM CAPTURE)
        'rolling_rate_10',              # Very recent activity (heating up?)
        'rolling_rate_20',              # Recent activity confirmation
        'rolling_trend_10',             # Trend direction (accelerating?)
        'rolling_trend_20',             # Trend confirmation

        # RECENT ACTIVITY WINDOWS
        'recent_4',                     # Last 4 draws
        'recent_14',                    # Last 14 draws

        # GAP PATTERNS
        'gap_consistency_score',        # Consistent appearance pattern
        'max_gap_ratio',                # Gap distribution

        # BONUS TRANSITION (for position 7)
        'was_recent_bonus',             # Bonus → main transition (74% rate)

        # TIMING-FOCUSED
        'recency_zone_score',           # Optimal window detection
        'appearance_volatility',        # Temporal consistency

        # CONSTRAINTS (ensure valid draws)

        'PAIRWISE_INTERACTIONS',       # Critical for logistic regression!
        'TRIPLE_INTERACTIONS',         # Category × freshness × timing patterns
    ],
    # Total: ~17 features focused on WHEN numbers appear

    # FEATURE SELECTION: Aggressive filtering for focused momentum signals
    'feature_selection': {
        'enable': True,
        'correlation_threshold': 0.95,   # Remove duplicates
        'importance_threshold': 0.01     # More aggressive (remove features <1% importance)
    },

    'diversity_penalty': 0.30,  # 30% soft penalty on previously selected numbers

    'algorithm_params': {
        'penalty': 'l2',
        'solver': 'liblinear',
        'max_iter': 1000,
        'random_state': 42,
        'C': 1.0
    },

    'calibration': {
        'method': 'sigmoid',
        'cv': 5
    }
}

MODEL_2_CONFIG = {
    'name': 'Jackpot Optimizer - 6-Ball Main Prize Specialist',
    'description': 'Trained ONLY on main 6 balls (excludes bonus) - focuses on stability and long-term patterns',
    'algorithm': 'random_forest',  # Better for complex interactions

    'hot_count': 3,
    'medium_count': 1,
    'cold_count': 2,
    'generic_count': 0,

    'features': [
        # CORE STABILITY (MUST HAVE)
        'total_count',                  # Long-term frequency
        'days_since_last',              # Time since appearance

        # LONG-TERM PATTERNS (STABILITY)

        # DISTRIBUTION FEATURES (STABILITY)

        # ADVANCED STABILITY
        'appearance_volatility',        # Consistency in frequency
        'gap_consistency_score',        # Predictable gaps
        'gap_variance',                 # Gap variance

        # ROLLING STATS (conservative windows for stability)
        'rolling_rate_50',              # Long-term rate
        'rolling_trend_50',             # Long-term trend

        # FRESHNESS PATTERNS
        FRESHNESS_PATTERN_WEIGHTS,      # Freshness interaction features

        # ADVANCED PATTERNS
        ADVANCED_PATTERN_FEATURES,      # Volatility and trend features

        # TIMING (conservative)
        'recency_zone_score',           # Optimal window
        'recent_14',                    # Longer window for stability

        # CONSTRAINTS

        # EXPLICITLY EXCLUDE BONUS FEATURES
        # ❌ NO 'was_recent_bonus' - not relevant for main 6 jackpot
        # ❌ NO 'bonus_to_main_*' - not relevant for main 6 jackpot
    ],
    # Total: ~20+ features focused on STABILITY for main 6 balls

    # FEATURE SELECTION: Use explicit list (no auto-selection)
    'feature_selection': {
        'enable': False,  # ⭐ Use explicit feature list as-is
        # Let model handle all stability signals
    },

    'diversity_penalty': 0.40,  # 40% soft penalty on previously selected numbers

    # Capacity is constrained on purpose. Unconstrained leaves at depth 10 gave a
    # train/val AUC gap of 0.383 over ~15,800 rows - memorised per-number patterns,
    # not signal. Depth 4 with leaves in the hundreds holds the gap near 0.06 and
    # leaves validation AUC where it was (C-15b).
    'algorithm_params': {
        'n_estimators': 100,
        'max_depth': 4,
        'min_samples_leaf': 300,
        'max_features': 0.5,
        'class_weight': 'balanced_subsample',
        'random_state': 42,
        'n_jobs': -1
    },

    'calibration': {
        'method': 'isotonic',  # Better for tree-based models
        'cv': 3
    }
}

MODEL_3_CONFIG = {
    'name': 'Complexity Explorer',
    'description': 'XGBoost with ALL features - finds complex interaction patterns across all signals',
    'algorithm': 'xgboost',

    'hot_count': 2,
    'medium_count': 2,
    'cold_count': 2,
    'generic_count': 0,

    'features': [
        # USE EVERYTHING - let XGBoost find complex patterns
        'total_count',
        'days_since_last',
        'recency_zone_score',

        # ALL ROLLING STATISTICS
        'rolling_rate_10',
        'rolling_rate_20',
        'rolling_rate_50',
        'rolling_trend_10',
        'rolling_trend_20',
        'rolling_trend_50',
        'gap_variance',
        'gap_cv',
        'appearance_acceleration',

        # ALL RECENT ACTIVITY
        'recent_4',
        'recent_14',

        # ALL GAP PATTERNS
        'gap_consistency_score',
        'max_gap_ratio',
        'appearance_volatility',

        # ALL BONUS FEATURES
        'was_recent_bonus',
        'days_since_bonus',

        # ALL PATTERN FEATURES
        FRESHNESS_PATTERN_WEIGHTS,
        ADVANCED_PATTERN_FEATURES,

        # ALL DISTRIBUTION FEATURES

        # ALL SERIES/CONSECUTIVE
        'has_consecutive_partner',

        # ALL CONSTRAINTS
        'freshness_weight_score',

        # Include everything available for maximum complexity detection
    ],
    # Total: 30-40 features - XGBoost will find which interactions matter

    # FEATURE SELECTION: DISABLED - keep everything for complexity
    'feature_selection': {
        'enable': False,  # ⭐ Use ALL features - complexity needs interactions
    },

    'diversity_penalty': 0.35,  # 35% soft penalty on previously selected numbers

    # Capacity is constrained on purpose, as for Model 2 (C-15b). Depth 3 with
    # min_child_weight=3 gave a train/val AUC gap of 0.165: complex patterns that do
    # not survive the validation window. Shallow, heavily shrunk and L2-penalised
    # trees hold the gap near 0.02 with validation AUC unchanged.
    'algorithm_params': {
        'n_estimators': 50,
        'max_depth': 2,
        'learning_rate': 0.03,
        'min_child_weight': 500,
        'reg_lambda': 20,
        'eval_metric': 'logloss',
        'random_state': 42,
        'n_jobs': -1,
        'subsample': 0.8,
        'colsample_bytree': 0.7
    },

    'calibration': {
        'method': 'isotonic',  # Better for tree-based models
        'cv': 3
    }
}

MODEL_4_CONFIG = {
    'name': 'Conservative Pool Generator',
    'description': 'Generates 20-number pool with HIGH-PRECISION features only - must contain 6+ winners',
    'algorithm': 'catboost',  # Best for high-precision predictions

    # Pool size = hot_count + medium_count + cold_count
    # UPDATED: 20-number pool
    'hot_count': 10,      # Top 7 hot
    'medium_count': 5,   # Top 9 medium
    'cold_count': 5,     # Top 4 cold
    'generic_count': 0,

    'features': [
        # ONLY PROVEN HIGH-IMPORTANCE FEATURES (top performers only)
        'days_since_last',              # #1 predictor (importance >0.15)
        'total_count',                  # #2 predictor (importance >0.15)
        'rolling_rate_20',              # #3 predictor (importance >0.12)
        'gap_consistency_score',        # #4 predictor (importance >0.12)
        'rolling_trend_10',             # #5 predictor (importance >0.10)

        # HIGH-CONFIDENCE INDICATORS ONLY

        # NO NOISY FEATURES (anything with importance < 0.02 excluded)
        # NO EXPERIMENTAL FEATURES
        # NO BONUS FEATURES (focus on reliable main ball patterns)
    ],
    # Total: ~12 features - only the most reliable predictors

    # FEATURE SELECTION: VERY AGGRESSIVE - keep only top performers
    'feature_selection': {
        'enable': True,
        'correlation_threshold': 0.90,   # Aggressive duplicate removal
        'importance_threshold': 0.02     # ⭐ VERY aggressive (only features >2% importance)
    },

    'diversity_penalty': 0.25,  # 25% soft penalty (for pool generator)

    'algorithm_params': {
        'iterations': 100,
        'depth': 6,
        'learning_rate': 0.1,
        'loss_function': 'Logloss',
        'random_seed': 42,
        'verbose': False,
        'thread_count': -1
    },

    'calibration': {
        'method': 'isotonic',  # Best for tree-based models
        'cv': 3
    }
}

ACTIVE_MODELS = [
    MODEL_1_CONFIG,
    MODEL_2_CONFIG,
    MODEL_3_CONFIG,
    MODEL_4_CONFIG,  # Add Model 4
]

SHOW_DETAILED_PENALTIES = True
SHOW_OVERLAP_ANALYSIS = True
SHOW_DATA_SOURCE_SUMMARY = False